FROM {{ registry | default('quay.io') }}/{{ project | default('pulp') }}/{{ item.value.base_image_name | default('pulp') }}:{{ item.value.tag | default('latest') }} as builder

RUN mkdir -p /etc/nginx/pulp
{% for plugin in item.value.plugin_snippets %}
RUN ln /usr/local/lib/python{{ item.value.python_version }}/site-packages/{{ plugin }}/app/webserver_snippets/nginx.conf /etc/nginx/pulp/{{ plugin }}.conf
{% endfor %}

FROM nginx:latest

RUN mkdir -p /etc/nginx/pulp
WORKDIR /etc/nginx/pulp
COPY --from=builder /etc/nginx/pulp .
WORKDIR /
