- hosts: localhost
  gather_facts: no
  vars:
    project_name: "{{ meta.namespace }}"
    database_connection:
      username: pulp
      password: pulp
    pulp_default_settings:
      databases:
        default:
          HOST: postgres
          ENGINE: django.db.backends.postgresql_psycopg2
          NAME: pulp
          USER: "{{ database_connection.username }}"
          PASSWORD: "{{ database_connection.password }}"
          PORT: 5432
          CONN_MAX_AGE: 0
      debug: "True"
      redis_host: redis
      redis_port:  6379
      redis_password: ''
#     content_origin: # Queried and set in pulp-api role
    deployment_state: present
    registry: quay.io
    project: pulp
    image: pulp
    tag: stable
    pulp_file_storage:
      access_mode: "ReadWriteMany"
      size: "100Gi"
  roles:
    - postgres
    - redis
    - pulp-api
    - pulp-content
    - pulp-resource-manager
    - pulp-worker
