#!/bin/bash -x

PULP_API_STATUS=$(/usr/bin/curl -I  http://pulp-api-svc:24817/pulp/api/v3/status/ | head -n 1|cut -d$' ' -f2)

echo $PULP_API_STATUS

PULP_CONTENT_STATUS=$(/usr/bin/curl -I  http://pulp-content-svc:24816/ | head -n 1|cut -d$' ' -f2)

echo $PULP_CONTENT_STATUS

if [[ "$PULP_API_STATUS" != "200" ]]; then
    exit 1
fi

if [[ "$PULP_CONTENT_STATUS" > "404" ]]; then
    exit 2
fi

exit 0

