# permissions for end users to edit pulps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulp-editor-role
rules:
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulps/status
  verbs:
  - get
