apiVersion: pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: example-pulp
spec:
  project: pulp
  # The image name (repo name) for the pulp image.
  image: pulp
  # The image tag for the pulp image.
  tag: latest
  pulp_file_storage:
    # k3s local-path requires this
    access_mode: "ReadWriteOnce"
    # We have a little over 40GB free on Travis VMs/instances
    size: "40Gi"
  database_connection:
    username: pulp
    password: pulp
    admin_password: pulp
