---
apiVersion: v1
kind: Secret
metadata:
  name: external-db-config
  namespace: db
  labels:
    app: external-db
data:
  POSTGRES_DB: cHVscA==
  POSTGRES_USER: cHVscC1hZG1pbg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRESQL_DATABASE: cHVscA==
  POSTGRESQL_USERNAME: cHVscC1hZG1pbg==
  POSTGRESQL_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-db-pvc
  namespace: db
  labels:
    app: external-db
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: db
  labels:
    app: external-db
spec:
  selector:
    matchLabels:
      app: external-db
  replicas: 1
  template:
    metadata:
      labels:
        app: external-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          envFrom:
          - secretRef:
              name: external-db-config
          env:
            - name: POSTGRES_INITDB_ARGS
              value: '--auth-host=scram-sha-256'
            - name: POSTGRES_HOST_AUTH_METHOD
              value: 'scram-sha-256'
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: external-db-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: db
  labels:
    app: external-db
spec:
  selector:
    app: external-db
  ports:
    - port: 5432
  type: ClusterIP
