---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cache
  name: cache
  namespace: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cache
    spec:
      affinity: {}
      containers:
      - image: redis:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - redis-cli -h 127.0.0.1 -p 6379
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - redis-cli -h 127.0.0.1 -p 6379
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /data
          name: example-pulp-redis-data
      securityContext: {}
      volumes:
      - emptyDir: {}
        name: example-pulp-redis-data
---
kind: Service
apiVersion: v1
metadata:
  name: cache
  namespace: cache
  labels:
    app.kubernetes.io/component: cache
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/component: cache
  sessionAffinity: None
  type: ClusterIP

