apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: galaxy-example
spec:
  deployment_type: galaxy
  image: quay.io/pulp/galaxy-minimal
  image_version: 4.6.3
  image_web: quay.io/pulp/galaxy-web
  image_web_version: 4.6.3
  admin_password_secret: "example-pulp-admin-password"
  signing_secret: "signing-galaxy"
  signing_scripts_configmap: "signing-scripts"
  storage_type: S3
  ingress_type: nodeport
  object_storage_s3_secret: example-pulp-object-storage
  # k3s local-path requires this
  file_storage_access_mode: "ReadWriteMany"
  # We have a little over 10GB free on GHA VMs/instances
  file_storage_size: "10Gi"
  pulp_settings:
    api_root: "/api/galaxy/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    aws_s3_endpoint_url: http://pulp_minio:9000
    telemetry: false
  api:
    replicas: 1
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
