apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: galaxy-example
spec:
  deployment_type: galaxy
  image: quay.io/pulp/galaxy-minimal
  image_version: 4.6.3
  image_web: quay.io/pulp/galaxy-web
  image_web_version: 4.6.3
  admin_password_secret: "example-pulp-admin-password"
  signing_secret: "signing-galaxy"
  signing_scripts_configmap: "signing-scripts"
  storage_type: S3
  ingress_type: nodeport
  nodeport_port: 30000
  object_storage_s3_secret: example-pulp-object-storage
  pulp_settings:
    token_server: http://nodeport.local:30000/token/
    content_origin: http://nodeport.local:30000
    ansible_api_hostname: http://nodeport.local:30000
    api_root: "/api/galaxy/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    aws_s3_endpoint_url: http://pulp_minio:9000
    analytics: false
  api:
    replicas: 1
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
