---
apiVersion: repo-manager.pulpproject.org/v1
kind: Pulp
metadata:
  name: example-pulp
spec:
  database:
    postgres_storage_class: standard

  file_storage_storage_class: standard
  file_storage_access_mode: "ReadWriteMany"
  file_storage_size: "2Gi"
