apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: ocp-example
spec:
  deployment_type: pulp
  admin_password_secret: "example-pulp-admin-password"
  ingress_type: route
  route_host: example.com
  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false
  api:
    replicas: 1
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi

  file_storage_access_mode: "ReadWriteMany"
  file_storage_size: "5Gi"
  file_storage_storage_class: azurefile-csi
  database:
    postgres_storage_class: azurefile-csi
