apiVersion: repo-manager.pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: ocp-example
spec:
  deployment_type: pulp
  admin_password_secret: "example-pulp-admin-password"
  storage_type: File
  ingress_type: route
  route_host: route_host_placeholder
  route_tls_termination_mechanism: edge
  # k3s local-path requires this
  file_storage_access_mode: "ReadWriteOnce"
  # We have a little over 10GB free on GHA VMs/instances
  file_storage_size: "10Gi"
  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false
  api:
    replicas: 1
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
