apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  storage_type: File
  # This doesn't really matter for minikube. Single node by design,
  # but the storage provisioner allows for ReadWriteMany. So let's
  # stick to our default.
  file_storage_access_mode: "ReadWriteMany"
  # The minikube VM won't go any larger.
  file_storage_size: "375Gi"
  # Default images:
  image: quay.io/pulp/pulp-minimal
  image_version: stable
  image_web: quay.io/pulp/pulp-web
  image_web_version: stable
