apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: example
spec:
  cache_enabled: true
  file_storage_access_mode: "ReadWriteMany"
  file_storage_size: "10Gi"
  ingress_type: Route
  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
  storage_type: File
  api:
    replicas: 1
  content:
    replicas: 2
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 2
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
