apiVersion: repo-manager.pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: example-pulp
spec:
  deployment_type: pulp
  image_version: nightly
  image_web_version: nightly
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1
  database:
    postgres_storage_class: standard
  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  file_storage_storage_class: standard
  cache:
    enabled: true
    redis_storage_class: standard
  ingress_type: nodeport
  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false
