apiVersion: repo-manager.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  image_version: nightly
  image_web_version: nightly
  no_log: false
  admin_password_secret: "example-pulp-admin-password"
  storage_type: File
  ingress_type: nodeport
  file_storage_access_mode: "ReadWriteMany"
  file_storage_size: "10Gi"
  container_token_secret: "container-auth"
  pulp_settings:
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi