apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: test-pulp
spec:
  telemetry:
    enabled: true
  deployment_type: pulp
  image_version: stable
  image_web_version: 3.63.4
  inhibit_version_constraint: true
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1
  migration_job:
    container:
      resource_requirements:
        requests:
          cpu: "250m"
        limits:
          cpu: "250m"

  database:
    postgres_storage_class: standard

  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  file_storage_storage_class: standard

  # Redis configs
  cache:
    enabled: true
    redis_storage_class: standard

  ingress_type: nodeport
  nodeport_port: 30001

  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false
    token_server: http://nodeport.local:30001/token/
    content_origin: http://nodeport.local:30001
    ansible_api_hostname: http://nodeport.local:30001

