apiVersion: repo-manager.pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: pulp
spec:
  deployment_type: pulp
  image_version: latest
  image_web_version: latest
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1

  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  signing_secret: "signing-galaxy"
  signing_scripts_configmap: "signing-scripts"
  image_web: "quay.io/pulp/galaxy-web"

  ingress_type: nodeport
  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp

  cache:
    enabled: true
    external_cache_secret: external-redis
