---
apiVersion: v1
data:
  REDIS_DB: ""
  REDIS_HOST: bXktcmVkaXMtaG9zdC5leGFtcGxlLmNvbQ==
  REDIS_PASSWORD: ""
  REDIS_PORT: NjM3OQ==
kind: Secret
metadata:
  name: external-redis
type: Opaque

---
apiVersion: repo-manager.pulpproject.org/v1
kind: Pulp
metadata:
  name: pulp
spec:

  database:
    external_db_secret: external-database

  file_storage_access_mode: "ReadWriteMany"
  file_storage_size: "2Gi"
  file_storage_storage_class: standard

  cache:
    enabled: true
    external_cache_secret: external-redis
