apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: pulp
spec:
  deployment_type: pulp
  cache_enabled: true
  image_version: nightly
  image_web_version: nightly
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: test
#            operator: In
#            values:
#            - test
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1

  database:
#    postgres_storage_requirements: "5Gi"

  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  file_storage_storage_class: "standard"
  signing_secret: "signing-galaxy"
  signing_scripts: "signing-scripts"
  image_web: "quay.io/pulp/pulp-web"

  redis_storage_class: standard

  ingress_type: nodeport

  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    # cache_enabled: true
    # db_encryption_key: "/etc/pulp/keys/database_fields.symmetric.key"
    # galaxy_collection_signing_service: ansible-default
    # ansible_certs_dir: "/etc/pulp/keys/"
    # databases:
    #   default:
    #     HOST: "pulp-database-svc.pulp.svc.cluster.local"
    #     ENGINE: django.db.backends.postgresql_psycopg2
    #     NAME: "pulp"
    #     USER: "pulp"
    #     PASSWORD: "{{ postgres_pass }}"
    #     PORT: "5432"
    #     CONN_MAX_AGE: 0
    #     OPTIONS:
    #       sslmode: "prefer"
    # redis_host: "pulp-redis-svc.pulp"
    # redis_port: 6379
    # redis_password: ""

  sso_secret: keycloak-config
