---
apiVersion: v1
kind: Secret
metadata:
  name: 'example-pulp-admin-password'
stringData:
  password: 'password'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  analytics: "False"

---
apiVersion: repo-manager.pulpproject.org/v1
kind: Pulp
metadata:
  name: example-pulp
spec:
  custom_pulp_settings: settings
  admin_password_secret: "example-pulp-admin-password"

  database:
    postgres_storage_class: managed-csi

  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  file_storage_storage_class: azurefile-csi

  ingress_type: route
  route_host: route_host_placeholder
