apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: example-pulp
spec:
  telemetry:
    enabled: true
  image_version: stable
  image_web_version: stable
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1
  database:
    postgres_storage_class: standard
  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  file_storage_storage_class: standard
  ingress_type: nodeport
  pulp_settings:
    api_root: "/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    analytics: false
