---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: pulp-manager
          image: testing
          env:
            - name: OPERATOR_SA_NAME
              value: osdk-sa
