---
- name: Generate token authentication keys
  shell: |-
    openssl ecparam -genkey -name prime256v1 -noout -out /tmp/private_key.pem
    openssl ec -in /tmp/private_key.pem -pubout -out /tmp/public_key.pem

- name: Create token authentication secret
  k8s:
    apply: true
    definition: "{{ lookup('template', 'pulp-container-auth.secret.yaml.j2') }}"
