---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
    - community.kubernetes

  tasks:
    - name: Delete namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent
        wait: yes

    - name: Delete RBAC resources
      k8s:
        definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
        namespace: '{{ namespace }}'
        state: absent
        wait: yes
      with_items:
        - service_account.yaml
        - role.yaml
        - cluster_role.yaml
        - role_binding.yaml
        - cluster_role_binding.yaml

    - name: Delete Custom Resource Definition
      k8s:
        definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/pulpproject_v1alpha1_pulp_crd.yaml'])) }}"
        state: absent
        wait: yes
