name: "Docs CI"

on:
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Install Test Dependencies"
        run: |
          pip install -r doc_requirements.txt
      - name: Build docs
        run: make docs
