name: Pulpcore Versions
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
jobs:
  pulpcore:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - PULPCORE_VERSION: latest
          - PULPCORE_VERSION: "3.85"
          - PULPCORE_VERSION: "3.73"
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/pre-reqs"
        with:
          minikube-version: v1.34.0

      - name: Deploy pulp-operator to K8s
        run: |
          make local
          kubectl get namespace
          kubectl config set-context --current --namespace=pulp-operator-system
          kubectl apply -f .ci/assets/kubernetes/pulp-admin-password.secret.yaml
          kubectl apply -f config/samples/k8s_versions_ci.yaml
          kubectl patch pulp example-pulp --type='merge' -p '{"spec":{"image_version":"${{ matrix.PULPCORE_VERSION }}","image_web_version":"${{ matrix.PULPCORE_VERSION }}"}}'

      - name: Check and wait pulp-operator deploy
        run: |
          journalctl --unit=pulp-operator -f &
          kubectl logs -f -l app.kubernetes.io/component=operator -c manager &
          kubectl wait --for condition=Pulp-Operator-Finished-Execution pulp/example-pulp --timeout=900s

      - name: Test all components
        run: |
          export INGRESS_TYPE=nodeport
          .ci/scripts/pulp_tests.sh -m
        shell: bash
        env:
          PY_COLORS: '1'

      - name: Logs
        if: always()
        run: .github/workflows/scripts/show_logs.sh
