---
name: Release Image
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-reqs
        with:
          deploy: true
      - name: Quay login
        env:
          QUAY_BOT_PASSWORD: ${{ secrets.QUAY_BOT_PASSWORD }}
          QUAY_BOT_USERNAME: pulp+github
        run: echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io
      - name: Build and Push images
        run: |
          export IMG=quay.io/pulp/pulp-operator:v${{ github.ref_name }}
          export CATALOG_IMG=quay.io/pulp/pulp-operator-catalog:v${{ github.ref_name }}
          export BUNDLE_IMG=quay.io/pulp/pulp-operator-bundle:v${{ github.ref_name }}
          make docker-buildx bundle-build bundle-push catalog-build catalog-push
        shell: bash
